[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200

; --- CONFIGURACIÓN DE SEGURIDAD ---
board_build.flash_mode = dio
board_build.f_flash = 40000000L

; --- COMENTA ESTA LÍNEA TEMPORALMENTE ---
board_build.partitions = partitions.csv


;platform = espressif32
;board = esp32dev
;framework = espidf
; AQUÍ ESTÁ EL TRUCO:
; "+" incluye archivos, "-" excluye archivos.
; Excluimos main.cpp y MaquinaEstados.cpp para que sus errores no detengan la prueba.
